environment:
  name: prod
  project: cdf-bootcamp-73-prod
  validation-type: prod
  selected:
  - modules/bootcamp/data_foundation/
  - modules/bootcamp/ice_cream_api/
  - modules/bootcamp/use_cases/oee/

variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space

      data_foundation:
        data_developer_source_id: d3e4b238-b7b8-4d61-81cb-50fcbe4bd213
        
      ice_cream_api:
        icapi_extractors_source_id: 201b4e13-281f-45c5-b60b-5b70b22901f4
        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}

      use_cases:
        oee:
          data_pipeline_oee_source_id: d0531d51-de18-43e6-b250-93181709f37d
          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
